changes steady receipe
SyzygyStation/Syzygy-Eris pull request #148
Opened 2020-09-21 04:08 UTC by bearrrrrrrr

About The Pull Request

changes steady from needing carpotoxin to needing roach chems 

## Why It's Good For The Game

Needing an RNG drop that you probably won't get for chemistry is lame. Half the time, the ship does not move. There is generally no carp on 60% of rounds. Sad!

## Changelog
```changelog
tweak: steady receipe change
```

2020-09-21 05:31 UTC, Michiyamenotehifunana requested changes
It appears that a line of code was accidentally deleted. Please try to restore it.

2020-09-21 05:31 UTC, Michiyamenotehifunana commented on code/modules/reagents/recipes.dm
> +
wtf is this

2020-09-21 21:15 UTC, bearrrrrrrr commented on code/modules/reagents/recipes.dm
> +
what the ufck-

2020-09-21 21:16 UTC, bearrrrrrrr commented
fixed
not sure wtf happened there lmao i guess i accidentally deleted it somehow

2020-09-22 06:30 UTC, Michiyamenotehifunana approved these changes
All good!

2020-09-22 23:19 UTC, merged