new storyteller: the Lookout
SyzygyStation/Syzygy-Eris pull request #165
Opened 2020-09-28 02:52 UTC by bearrrrrrrr

## About The Pull Request

Adds a new storyteller: The Lookout.

## Why It's Good For The Game

add: Adds The Lookout, a storyteller that will spawn antagonists and then go silent to let the crew make their own drama. Needs playtesting.

## Changelog
```changelog
add: Adds The Lookout, a storyteller that will spawn antagonists and then go silent to let the crew make their own drama. Needs playtesting.
```

2020-09-28 02:59 UTC, Torque4607 approved these changes
The code looks good, just needs approval admin-side to merge.

2020-09-28 03:00 UTC, bearrrrrrrr commented
SPEEEEEEEEDMEEEEEEEEEEEEEEEEEERGE

2020-09-28 03:01 UTC, Torque4607 commented
This is basically Bay's `secret` gamemode.

2020-09-28 03:07 UTC, Michiyamenotehifunana requested changes

2020-09-28 03:07 UTC, Michiyamenotehifunana commented on zzz_modular_syzygy/storytellers/lookout.dm
> +/datum/storyteller/tyrant  //This objective of this storyteller is to spawn antagonists at round-start, and then be quiet to let the crew roleplay and create their own drama.
You forgot to rename the typepath

2020-09-28 03:09 UTC, Torque4607 commented
Hurk, guess I'm just blind.

2020-09-28 03:22 UTC, bearrrrrrrr commented on zzz_modular_syzygy/storytellers/lookout.dm
> +/datum/storyteller/tyrant  //This objective of this storyteller is to spawn antagonists at round-start, and then be quiet to let the crew roleplay and create their own drama.
done

2020-09-28 03:48 UTC, Michiyamenotehifunana approved these changes
Looking good.

2020-09-28 03:51 UTC, Michiyamenotehifunana requested changes
Wait is this actually included in the .dme? Is The Lookout even going to be compiled? Did you even test this bear why

2020-09-28 06:36 UTC, bearrrrrrrr commented
should be good now.

2020-09-29 03:59 UTC, Michiyamenotehifunana approved these changes
can confirm, is good now

2020-09-29 22:49 UTC, merged