Defibrillator Touchup Patch
SyzygyStation/Syzygy-Eris pull request #201
Opened 2020-10-16 12:53 UTC by Michiyamenotehifunana

## About The Pull Request

This PR ports some defib stuff from Eclipse, and also makes it so that core implants are reactivated on defib. Among the things to note:
1) Defib timers should now actually function. They no longer run off the brain, but just the mob's listed time of death.
2) Defibs will now heal 50 oxyloss on revive. Seeing as ours are explicitly AEDs designed to be used by random passerbys, this should make it much easier for people to use them without greytiding and grabbing extra inapprovaline and dexalin.

**THESE CHANGES REMAIN UNTESTED.**
However, the core functionality of defibs remain untouched, and even if the new additions fuck up, they should not break defibs in general.

## Why It's Good For The Game

General quality of life improvements to defib usage. No more instant death upon defibbing. No more having to rely on an acolyte or admin to reactivate your cruciform.

## Changelog
```changelog Toriate
tweak: cruciforms now reactivated by defibs
fix: defib timers now function, no more defibbing 5 hour old rotting corpses
balance: defibs will now heal oxyloss
```

2020-10-18 16:52 UTC, ShadzFen approved these changes
It's not been tested and I'd rather it be tested tbh, but the code does look fine. Hopefully nothing breaks.

2020-10-19 18:37 UTC, ShadzFen requested changes
Fish denied the merge, you're gonna have to go test it first and confirm what works and what doesn't.

2020-10-29 09:38 UTC, Michiyamenotehifunana commented
Tested, fixed, and tested again. Working just fine now.

2020-10-29 18:48 UTC, ShadzFen approved these changes
Very cool! Looking forward to this one. All good, modular fixes to defibs. Good to go.

2020-10-29 21:09 UTC, merged