Randomizes the License point value for oldified disks.
SyzygyStation/Syzygy-Eris pull request #211
Opened 2020-10-20 17:21 UTC by ZeroNetAlpha

## About The Pull Request
All this does is add a specific oldification for the design disks that makes the disks have a 90% chance of having anywhere between 3 and 3 less than the maximum value of LP for any old disks.

## Why It's Good For The Game
Disks in the trash shouldn't have the full amount of license points. 

## Changelog
```changelog
balance: Balances the old disks to not be as good as just a regular, untarnished disks, 

```

2020-10-20 17:28 UTC, ZeroNetAlpha commented
i saw that it failed. fixing now.

2020-10-20 17:43 UTC, Jamini commented
This can and should be modularized. You can just take your new make_old proc and put it in its own file in the modular folder.

2020-10-20 21:45 UTC, Michiyamenotehifunana requested changes
Looks well modularized, just needs a couple touchups.

2020-10-20 21:45 UTC, Michiyamenotehifunana commented on zzz_modular_syzygy/code/modules/scrap/oldificator.dm
> +	if (.)
This check doesn't look entirely necessary.

2020-10-20 21:45 UTC, Michiyamenotehifunana commented on zzz_modular_syzygy/code/modules/scrap/oldificator.dm
> +		if(prob(90))
Indent here looks messed up. Also, combine this with the if check under it. `if(license > 0 && prob(90))`

2020-10-20 21:45 UTC, Michiyamenotehifunana commented on zzz_modular_syzygy/code/modules/scrap/oldificator.dm
> +			if(license > -1)
Should check if its `>0` instead.

2020-10-22 07:53 UTC, Michiyamenotehifunana approved these changes
Looks good. There's a non-modular bit of whitespace change that I _know_ Git is dumb enough to conflict on, but it's trivial enough to not matter.

2020-10-23 00:14 UTC, merged